zhipu:
  api-key: "e53ae59585a343ed87efb11bb966f544.sVcT03J7VJXiJe3t"
  model: "glm-4.7"
  temperature: 0.2
  max-tokens: 2048
mock:
  upload-dir: "uploads"
filter:
  keywords: "api,接口,request,response,header,body,parameter,params,sample,example,url,method,请求,响应,参数,示例,地址,接口地址"
  url-regex: "(https?://|/)[\\w\\-./:?&=%#]+"
spring:
  datasource:
    url: "jdbc:mysql://10.18.40.27:3306/db_mock?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "redtea.123"
  jpa:
    hibernate:
      ddl-auto: "update"
  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "50MB"